GET http://localhost:5050/realtimeDb/1
Accept: application/json

###

###
POST http://localhost:5050/loadDatabases
Content-Type: application/json

[
    {
      "id": 1,
      "appName": "Money Easy Database",
      "serviceAccountPath": "C:\\Users\\Jithendra.Thenuwara\\Downloads\\super-pass-64e2b-firebase-adminsdk-7zxq2-61f3d182fe.json",
      "databaseUrl": "https://super-pass-64e2b-default-rtdb.europe-west1.firebasedatabase.app"
    }
]


###
